name: dart_validator
version: 1.0.3
authors:
- Lucas Yarid <lucas.yarid@gmail.com>
- Giovanni Spolidorio <spolidorio@gmail.com>
description: >
  A package to validate strings and input data for dart with a variety of validators such as cpf, cnpj, car plate, email, phone number and others.
homepage: https://github.com/the-cyg/dart_validator

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter