name: flux_validator_dart
version: 2.0.0
description: >
  A package to validate strings and input data for dart with a variety of validators such as cpf, cnpj, car plate, email, phone number and others.
homepage: https://github.com/this-empathy/dart_validator

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter